[project]
name = "python3"
version = "0.1.0"
description = "LeetCode"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.ruff.lint]
# 全局忽略 F403 (unable to detect undefined names)
ignore = ["E402", "F403","F405"]
